# Generated by Django 6.0 on 2026-03-20 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie_id'], name='ratings_rat_movie_i_357fbe_idx'),
        ),
    ]
