# Generated by Django 6.0 on 2026-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='spoiler_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
