# Generated by Django 6.0 on 2026-04-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_has_spoiler_review_spoiler_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spoiler_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
