# Generated by Django 6.0 on 2026-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_is_hidden_review_is_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_spoiler_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
