# Generated by Django 6.0 on 2026-04-02 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', 'is_accepted'], name='social_foll_followe_78a9ff_idx'), models.Index(fields=['following', 'is_accepted'], name='social_foll_followi_069720_idx'), models.Index(fields=['is_accepted', 'created_at'], name='social_foll_is_acce_50d260_idx'), models.Index(fields=['created_at'], name='social_foll_created_5df765_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
