# Generated by Django 6.0 on 2026-04-10 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'is_accepted', 'created_at'], name='social_foll_followe_7afa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', 'is_accepted', 'created_at'], name='social_foll_followi_04b9c0_idx'),
        ),
    ]
